name: Reusable Workflow | Test SDK Core

on:
  workflow_call:
    inputs:
      subgraph-release:
        required: true
        type: string

jobs:
  test-sdk-core:
    name: Test SDK-Core

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: "Install dependencies"
        run: pnpm install --frozen-lockfile

      - name: "Build contracts"
        run: yarn build:contracts
        working-directory: ./packages/ethereum-contracts

      - name: "Run test suite"
        run: |
          yarn generate-graphql-schema:${{ inputs.subgraph-release }}
          yarn test
        working-directory: ./packages/sdk-core
        env:
          SUBGRAPH_RELEASE_TAG: ${{ inputs.subgraph-release }}